### ISSUE TITLE
Deployment fails when Hipchat API is down

### ISSUE THREAD

**Issue by blimmer** [blimmer/ember-cli-deploy-hipchat#6]
```
› ember deploy staging
version: 2.4.2
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
- Listing revisions for key: `my-app:index`
Deploying [============🚀 -] 94% [plugin: hipchat -> didDeploy]Error: HipChat API Error.
Error: HipChat API Error.
    at requestCallback (/Users/blimmer/code/my-app/node_modules/ember-cli-deploy-hipchat/node_modules/hipchatter/hipchatter.js:323:35)
    at ClientRequest.<anonymous> (/Users/blimmer/code/my-app/node_modules/ember-cli-deploy-hipchat/node_modules/hipchatter/node_modules/needle/lib/needle.js:293:21)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketCloseListener (_http_client.js:247:9)
    at TLSSocket.emit (events.js:129:20)
Deploying [=============🚀 ] 100% [plugin: hipchat -> didFail]
Pipeline aborted
```

**Comment by blimmer** [comment]
If the service is unavailable, don't worry about it.
